# backend/config/routes.yaml

admin_dashboard:
    path: /admin
    controller: App\Controller\AdminController::dashboard

# Site management routes
admin_sites:
    resource: App\Controller\SiteController
    type: annotation

# Page management routes  
admin_pages:
    resource: App\Controller\PageController
    type: annotation

# Module management routes
admin_modules:
    resource: App\Controller\ModuleController
    type: annotation

# Settings routes
admin_settings:
    resource: App\Controller\SettingsController
    type: annotation

# Feedback routes
feedback:
    resource: App\Controller\FeedbackController
    type: annotation

# Demo routes
demo:
    resource: App\Controller\DemoController
    type: annotation