services:
    App\Service\DemoService:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
    
    App\Service\FeedbackService:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
    
    App\Repository\SiteRepository:
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments:
            - App\Entity\Site

    App\Repository\PageRepository:
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments:
            - App\Entity\Page

    App\Repository\ModuleInstanceRepository:
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments:
            - App\Entity\ModuleInstance

    App\Form\SiteType:
        tags: ['form.type']

    App\Form\PageType:
        tags: ['form.type']

    App\Form\SettingsType:
        tags: ['form.type']